modLoader="javafml"
loaderVersion="${fml_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Puqns67/SkinTypeFix/issues"

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
displayURL="https://modrinth.com/mod/skintypefix"
logoFile="assets/${mod_id}/logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	side="CLIENT"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
	versionRange="${neoforge_version_range}"
    side="CLIENT"
